"""Profile loader — reads profile.yaml and renders it into a scoring prompt block.

Priority order:
  1. ~/.job_pipeline/profile.yaml  (structured YAML — generated by `metis init`)
  2. ~/.job_pipeline/profile.md    (legacy free-text — still supported)
  3. Inline fallback stub           (last resort, not used in practice)
"""
from __future__ import annotations
import logging
from pathlib import Path

log = logging.getLogger(__name__)

import os as _os
PROFILE_DIR  = Path.home() / ".job_pipeline"
# METIS_PROFILE env var lets dev/test tooling point at a different profile
# without touching the real profile.yaml — never set this in production.
YAML_PATH    = Path(_os.environ["METIS_PROFILE"]) if "METIS_PROFILE" in _os.environ else PROFILE_DIR / "profile.yaml"
MD_PATH      = PROFILE_DIR / "profile.md"


def _data_dir() -> Path:
    """Resolve state dir at call time so tests/personas can patch env safely."""
    return Path(_os.environ["METIS_DATA_DIR"]) if "METIS_DATA_DIR" in _os.environ else PROFILE_DIR


# ---------------------------------------------------------------------------
# YAML loader + renderer
# ---------------------------------------------------------------------------

def load_profile_yaml() -> dict | None:
    """Return the profile dict if profile.yaml exists and parses cleanly."""
    if not YAML_PATH.exists():
        return None
    try:
        import yaml  # pyyaml — installed via requirements
        data = yaml.safe_load(YAML_PATH.read_text())
        log.info(f"Loaded profile from {YAML_PATH}")
        return data
    except Exception as e:
        log.warning(f"Failed to parse {YAML_PATH}: {e}")
        return None


def render_profile(data: dict) -> str:
    """Convert a profile.yaml dict into a human-readable scoring prompt block."""
    c  = data.get("candidate", {})
    t  = data.get("target", {})
    sc = data.get("scoring", {})

    name     = c.get("name", "Candidate")
    location = c.get("location", "")

    # Location preference — priority: new field > legacy work_mode list > legacy bool
    loc_pref = c.get("location_preference")
    work_mode_list = c.get("work_mode") or []
    if loc_pref:
        remote = {"remote": "remote only", "local": "local / open to onsite", "flexible": "flexible on location"}.get(loc_pref, loc_pref)
    elif work_mode_list:
        remote = ", ".join(work_mode_list)
    elif c.get("open_to_remote"):
        remote = "remote-friendly"
    else:
        remote = "on-site preferred"

    reloc      = ", ".join(c.get("open_to_relocation", []))
    level      = t.get("level", "")
    roles      = ", ".join(t.get("roles", []))
    industries = ", ".join(t.get("industries", []))

    apply_t    = sc.get("solid_match_threshold", sc.get("apply_threshold", 75))
    consider_t = sc.get("moderate_match_threshold", sc.get("consider_threshold", 55))

    lines = [
        f"CANDIDATE: {name} — actively searching",
        f"TARGET LEVEL: {level} — {roles}",
        f"LOCATION: {location}; {remote}",
    ]
    if reloc:
        lines.append(f"OPEN TO RELOCATION: {reloc}")
    if industries:
        lines.append(f"PREFERRED INDUSTRIES: {industries}")

    # Aspirations — track, direction, company types
    asp = data.get("aspirations", {})
    if asp:
        lines += ["", "ASPIRATIONS:"]
        if asp.get("track"):
            lines.append(f"Track: {asp['track']}")
        if asp.get("direction"):
            lines.append(asp["direction"].strip())
        if asp.get("company_types"):
            lines.append(f"Drawn to: {', '.join(asp['company_types'])}")
        if asp.get("avoid_company_types"):
            lines.append(f"Avoid company types: {', '.join(asp['avoid_company_types'])}")

    # Soft preferences — stage, industry nudges, aspirational salary
    pref = data.get("preferences", {})
    if pref:
        lines += ["", "PREFERENCES (soft signals — nudge ranking, don't disqualify):"]
        if pref.get("company_stage"):
            lines.append(f"Stage preference: {', '.join(pref['company_stage'])}")
        if pref.get("industry_targets"):
            lines.append(f"Move toward: {', '.join(pref['industry_targets'])}")
        if pref.get("industry_avoid"):
            lines.append(f"Steer away from: {', '.join(pref['industry_avoid'])}")
        if pref.get("base_salary_target_usd"):
            lines.append(f"Target base salary: ${pref['base_salary_target_usd']:,}")

    lines += [
        "",
        "SCORE CALIBRATION:",
        f"Apply threshold: {apply_t}+.  Consider: {consider_t}+.",
    ]

    # Inferred background — used by Layer 1/2 for domain and gate grounding
    inferred = data.get("inferred", {})
    if inferred:
        inf_parts = []
        if inferred.get("customer_types"):
            inf_parts.append(f"customer context: {', '.join(inferred['customer_types'])}")
        if inferred.get("degree_level"):
            inf_parts.append(f"degree held: {inferred['degree_level']}")
        if inf_parts:
            lines += ["", f"INFERRED BACKGROUND: {'; '.join(inf_parts)}"]

    if data.get("notes"):
        lines += ["", data["notes"].strip()]

    exp = data.get("experience", [])
    if exp:
        lines += ["", "EXPERIENCE:"]
        for e in exp:
            lines.append(
                f"- {e.get('company', '')}: {e.get('title', '')} ({e.get('dates', '')})"
            )
            for h in e.get("highlights", []):
                lines.append(f"    • {h}")

    edu = data.get("education", [])
    if edu:
        lines += ["", "EDUCATION:"]
        for e in edu:
            inst = e.get("institution") or ""
            deg  = e.get("degree", "")
            yr   = e.get("year")
            entry = f"- {deg}"
            if inst:
                entry += f" — {inst}"
            if yr:
                entry += f" ({yr})"
            lines.append(entry)

    strengths = data.get("strengths", [])
    if strengths:
        lines += ["", "CORE STRENGTHS:"]
        lines += [f"- {s}" for s in strengths]

    skills = c.get("skills", [])
    if skills:
        lines += ["", "SKILLS & TOOLS:"]
        lines += [f"- {s}" for s in skills]

    certs = c.get("certifications", [])
    if certs:
        lines += ["", "CERTIFICATIONS:"]
        lines += [f"- {s}" for s in certs]

    for key, label in [
        ("green_flags",  "GREEN FLAGS"),
        ("yellow_flags", "YELLOW FLAGS"),
        ("red_flags",    "RED FLAGS"),
    ]:
        flags = data.get(key, [])
        if flags:
            lines.append(f"\n{label}: {'; '.join(flags)}")

    if data.get("deal_breakers"):
        lines.append(f"\nDEAL BREAKERS: {', '.join(data['deal_breakers'])}")

    if data.get("salary_floor_usd"):
        sal = f"${data['salary_floor_usd']:,}"
        if data.get("salary_is_hard_floor"):
            lines.append(f"\nSALARY FLOOR: {sal} (hard minimum — flag roles confirmed below this)")
        else:
            lines.append(f"\nSALARY TARGET: {sal} (aspirational — undisclosed comp is not a concern)")

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Unified loader — called by score.py
# ---------------------------------------------------------------------------

def load_profile_text() -> str | None:
    """Return profile as a prompt-ready string, or None if nothing found.

    Tries YAML first (structured, generated by metis init), then
    falls back to the legacy free-text profile.md.
    Appends ~/.job_pipeline/feedback.md if it exists — user calibration notes
    that shape scoring without modifying the profile itself.
    """
    # 1. YAML (preferred)
    data = load_profile_yaml()
    profile_text = render_profile(data) if data else None

    # 2. Legacy markdown fallback
    if not profile_text and MD_PATH.exists():
        content = MD_PATH.read_text().strip()
        if content:
            log.info(f"Loaded profile from {MD_PATH} (legacy)")
            profile_text = content

    if not profile_text:
        return None

    # 3. Append feedback notes if present
    feedback_path = _data_dir() / "feedback.md"
    if feedback_path.exists():
        feedback = feedback_path.read_text().strip()
        if feedback:
            profile_text += (
                "\n\n"
                "CANDIDATE CALIBRATION FEEDBACK:\n"
                "The candidate has provided these scoring notes from past runs.\n"
                "Use them to adjust your judgment — they take precedence over generic defaults:\n\n"
                + feedback
            )
            log.info("Loaded scoring feedback from feedback.md")

    return profile_text
