from __future__ import annotations
import re, json, logging, time
from pathlib import Path
import anthropic

log = logging.getLogger(__name__)

# MODEL is read from pipeline.py at call time — passed in via the client object.
# Keep a local reference for the score_jobs_batch call.
import os
MODEL           = os.getenv("MODEL",           "claude-sonnet-4-6")
PRESCREEN_MODEL = os.getenv("PRESCREEN_MODEL", "claude-haiku-4-5")

WEIGHTS: dict[str, float] = {
    "seniority_scope":      0.25,
    "experience_relevance": 0.20,
    "compensation_fit":     0.15,
    "culture_values":       0.15,
    "domain_background":    0.15,
    "company_stage":        0.10,
}

# ---------------------------------------------------------------------------
# Profile — priority order:
#   1. ~/.job_pipeline/profile.yaml  (structured; generated by `metis init`)
#   2. ~/.job_pipeline/profile.md    (legacy free-text; still supported)
#
# No profile found → hard error pointing to `metis init`.
# ---------------------------------------------------------------------------

def _load_profile() -> str:
    from .profile import load_profile_text
    text = load_profile_text()
    if text:
        return text
    raise FileNotFoundError(
        "No profile found at ~/.job_pipeline/profile.yaml\n"
        "Run `metis init` to create one from your resume."
    )


def _candidate_name() -> str:
    """Extract candidate name from profile.yaml, or return generic fallback."""
    try:
        from .profile import load_profile_yaml
        data = load_profile_yaml()
        if data:
            return data.get("candidate", {}).get("name", "the candidate")
    except Exception:
        pass
    return "the candidate"


# ---------------------------------------------------------------------------
# Pre-screen — fast Haiku pass on title+company only (no JD fetch)
# ---------------------------------------------------------------------------

def _build_prescreen_context() -> str:
    """Minimal profile context for pre-screening.

    Intentionally excludes seniority level and target role titles — the pre-screen
    only sees title+company (no JD), so it cannot reliably assess scope. A "Senior PM"
    role may be staff-scope in practice; filtering on level here causes false negatives.
    Only deal-breakers that are inferable from title+company alone are included.
    """
    try:
        from .profile import load_profile_yaml
        data = load_profile_yaml() or {}
    except Exception:
        return ""

    target_roles = data.get("target", {}).get("roles", [])
    # Use first target role as the function signal; fall back to PM for legacy profiles.
    function_hint = target_roles[0] if target_roles else "Product Management"

    # Derive the job function label for the filter instruction.
    # Be explicit about common confusable pairs so Haiku doesn't conflate them.
    fn_lower = function_hint.lower()
    if "designer" in fn_lower or "design" in fn_lower:
        function_label = "Product Design / UX Design"
        not_function = (
            "Product Manager, Program Manager, Data Scientist, Engineer, or any non-design role. "
            "NOTE: 'Product Designer' and 'Product Manager' are DIFFERENT functions — filter PM roles."
        )
    elif "engineer" in fn_lower or "ml" in fn_lower or "machine learning" in fn_lower:
        function_label = "Engineering / ML Engineering"
        not_function = "Product Manager, Data Analyst, or non-engineering roles"
    else:
        function_label = function_hint
        not_function = "completely unrelated functions (e.g., Finance, Legal, Marketing)"

    lines: list[str] = [
        f"Candidate is seeking: {function_label} roles (e.g. {function_hint}).",
        f"Filter ONLY if the role is clearly NOT {function_label} — i.e. it is a {not_function}.",
        "When in doubt, PASS the role through (do not over-filter).",
    ]

    deal_breakers = data.get("deal_breakers", [])
    if deal_breakers:
        lines.append("Hard no (flag if obviously matched by title/company): "
                     + "; ".join(str(d) for d in deal_breakers[:6]))

    return "\n".join(lines)


def estimate_cost(n: int) -> str:
    """Human-readable Sonnet cost range for scoring n jobs (upper bound before pre-screen).

    Exported so pipeline.py can reference this single source of truth for cost estimates.
    """
    lo, hi = n * 0.005, n * 0.015
    return f"${lo:.2f}–${hi:.2f}"


def estimate_cost_hi(n: int) -> float:
    """Upper-bound cost estimate as a float — used by the cost gate in pipeline.py."""
    return n * 0.015


def _recover_partial_json(raw: str) -> list[dict]:
    """Salvage individual job objects from a truncated JSON array.

    Walks the raw string tracking brace depth so each complete {...} block
    can be parsed independently, returning whatever objects are valid.
    """
    objects: list[dict] = []
    depth, start = 0, None
    for i, ch in enumerate(raw):
        if ch == "{":
            if depth == 0:
                start = i
            depth += 1
        elif ch == "}":
            depth -= 1
            if depth == 0 and start is not None:
                try:
                    obj = json.loads(raw[start : i + 1])
                    if isinstance(obj, dict):
                        objects.append(obj)
                except json.JSONDecodeError:
                    pass
                start = None
    return objects


def prescreen_jobs_batch(client: anthropic.Anthropic, jobs: list[dict]) -> list[dict]:
    """Fast Haiku pre-screen on title+company only — filters obvious mismatches before
    JD enrichment and full Sonnet scoring.

    Returns the subset of jobs worth scoring.  Falls back to the full list if
    the API call fails or the response cannot be parsed.
    """
    if not jobs:
        return jobs

    context = _build_prescreen_context()
    if not context:
        log.warning("Pre-screen: no profile context — skipping filter")
        return jobs

    job_lines = "\n".join(
        f"{i + 1}. {j['title']} at {j['company']}"
        for i, j in enumerate(jobs)
    )

    try:
        response = client.messages.create(
            model=PRESCREEN_MODEL,
            max_tokens=max(256, len(jobs) * 12),  # ~12 tok/job: "1. Y\n" with headroom
            system=(
                f"{context}\n\n"
                "Quick function filter. For each numbered job output only the number "
                "and Y or N — nothing else.\n"
                "N = the role is clearly the WRONG function for this candidate "
                "(see candidate target above). OR the title+company obviously matches "
                "a hard-no deal-breaker above.\n"
                "Y = the role is the RIGHT function or close enough to warrant a full JD review. "
                "Never filter on seniority level — scope must be assessed from the full JD, not the title.\n"
                "When uncertain, Y."
            ),
            messages=[{"role": "user", "content": job_lines}],
        )
    except Exception as exc:
        log.warning(
            "Pre-screen API call failed (%s) — skipping filter, proceeding with all %d roles. "
            "Estimated Sonnet cost: ~$%.4f",
            exc, len(jobs), estimate_cost(len(jobs)),
        )
        return jobs

    raw   = response.content[0].text.strip()
    usage = response.usage
    log.info(
        f"Pre-screen ({PRESCREEN_MODEL}) — "
        f"input: {usage.input_tokens} tok, output: {usage.output_tokens} tok"
    )

    # Parse lines like "1. Y", "2. N", "3 Y", "4) N", etc.
    passed:   list[dict] = []
    filtered: list[str]  = []
    matched:  set[int]   = set()
    for line in raw.splitlines():
        m = re.match(r"(\d+)[.):\s]+([YN])", line.strip(), re.IGNORECASE)
        if m:
            idx     = int(m.group(1)) - 1
            verdict = m.group(2).upper()
            if 0 <= idx < len(jobs) and idx not in matched:
                matched.add(idx)
                if verdict == "Y":
                    passed.append(jobs[idx])
                else:
                    filtered.append(f"{jobs[idx]['title']} at {jobs[idx]['company']}")

    if not passed and not filtered:
        log.warning(
            "Pre-screen: response couldn't be parsed — proceeding with all %d roles. "
            "Estimated Sonnet cost: ~$%.4f",
            len(jobs), estimate_cost(len(jobs)),
        )
        return jobs

    log.info("Pre-screen: %d/%d passed (%d filtered out)", len(passed), len(jobs), len(filtered))
    if filtered:
        log.info("Pre-screen filtered:\n  " + "\n  ".join(filtered))
    return passed


# ---------------------------------------------------------------------------
# Full scoring (Sonnet)
# ---------------------------------------------------------------------------

def _build_bullet_style_guide(profile_data: dict) -> str:
    """Build bullet writing rules from the candidate's actual profile data.

    Generated dynamically so proof points and examples reference this specific
    candidate — not any hardcoded name, company, or product vocabulary.
    """
    candidate  = profile_data.get("candidate", {})
    name       = candidate.get("name", "the candidate")
    first      = name.split()[0]
    strengths  = profile_data.get("strengths", [])
    experience = profile_data.get("experience", [])

    # All proof points — no positional cap; Claude selects JD-relevant ones
    proof_lines = (
        "\n".join(f"  - {s}" for s in strengths)
        if strengths else
        "  (no strengths listed in profile — infer from experience section above)"
    )

    # Experience vocabulary from all roles
    exp_lines = []
    for e in experience:
        title = e.get("title", "")
        co    = e.get("company", "")
        hls   = e.get("highlights", [])
        label = f"{title} at {co}" if co else title
        if label:
            detail = hls[0][:80] if hls else ""
            exp_lines.append(f"  - {label}" + (f": {detail}" if detail else ""))
    exp_vocab = (
        "\n".join(exp_lines)
        if exp_lines else
        "  (see experience section in the profile above)"
    )

    # Good example: first strength, trimmed cleanly at a word boundary
    if strengths:
        s = strengths[0]
        if len(s) > 95:
            s = s[:95]
            s = s[: s.rfind(" ")].rstrip(" ,.")
        good_leverage = f'"{s}."'
    else:
        good_leverage = f'"{first} shipped [specific feature] at [company], which directly covers [JD requirement]."'

    return f"""BULLET WRITING RULES — follow exactly for every leveragePoint and frictionPoint:

1. HARD LENGTH LIMIT: 15–20 words maximum. Count every word before writing. Cut until it fits.
   If a sentence exceeds 20 words, it is wrong — rewrite it, do not submit it.
2. NO em-dash constructions. "topic — evidence — more evidence" is banned. One clause only.
3. Lead with the specific skill or fact; name something concrete from the JD.
4. SECOND-PERSON ALWAYS. Address the reader directly — "You shipped", "Your beta program", "You hold".
   Never use "{first}" or any third-person framing in bullet text.
   Third-person pronouns (she/her/he/him/they/them) are also banned.
   Possessive: "Your MCS in Data Science..." not "{first}'s MCS..." or "Her MCS...".
5. Active verb + correct tense:
   - Candidate's past actions → simple past: "shipped", "led", "built", "ran", "delivered".
   - Role requirements / what the JD asks for → present: "requires", "covers", "fits", "applies to".
   - Never mix: "You shipped X, which shows Y" is correct; "You ship X" for a past act is wrong.
6. Specific over generic: name a product, metric, customer type, or technology.
   "at scale" is banned — replace with the actual scale: "across 2,000+ models", "for 350+ customers".
7. NEVER mention score adjustments, deductions, multipliers, or numerical scoring mechanics.
8. Auto-delete on sight: directly, directly applicable, directly relevant, mapping directly,
   effectively, successfully, uniquely, seamlessly, exactly, robust, leverage (as verb),
   synergy, alignment (unless quoting a JD requirement), "at scale" (use the specific number).

PROOF POINTS — full list; select the 2 most relevant to THIS JD's stated requirements:
Do not default to the most prominent-sounding entries. If a less-prominent entry is a
closer match to what the JD specifically asks for, cite that one instead.
{proof_lines}

EXPERIENCE VOCABULARY — cite these when writing "You [verb]..." bullets:
{exp_vocab}

BAD (these are wrong — reject before submitting):
  ✓  "{first} built AI features at DocuSign — mapping directly to the JD."  [third-person + em-dash + "directly"]
  ✓  "{first}'s MCS in Data Science satisfies the degree requirement."  [third-person possessive]
  ✓  "You build AI features at DocuSign..."  [present tense for a past action]
  ?  "There may be some leveling uncertainty worth exploring."  [vague, no concrete fact]

GOOD (15–20 words, second-person, correct tense, no em-dash):
  ✓  "You {{good_leverage_verb}} — fits {{jd_requirement}}."  [past act → present fit]
  ?  "The title sits below your Staff/Principal target — verify scope and comp before applying." """


def _build_score_suffix(name: str, apply_t: int, consider_t: int, salary_is_hard_floor: bool = False) -> str:
    """Static scoring rubric, output schema, and thresholds — same structure for every user."""
    return f"""SCORING RUBRIC — score six dimensions (0–100 each), then compute weighted total:

  seniority_scope     (0.25)  Does the scope, ownership language, and structural level
                               match the candidate's target level? Use extracted
                               inferred_structural_level, manages_pm_team, reports_to_level.

  experience_relevance (0.20)  How well does the JD's required stack and depth match
                               the candidate's background? Target 70–80% overlap: 100% overlap
                               scores ~85 (no growth headroom), not 100.

  compensation_fit    (0.15)  {"Does total comp clear the hard salary floor? If salary_disclosed=false, cap this dimension at 60 — cannot assess without numbers. Use comp:undisclosed amber tag when salary is not disclosed." if salary_is_hard_floor else "Does total comp land attractively relative to the salary target? Salary is aspirational, not a hard gate. If salary_disclosed=false, score 65 (neutral — absence of disclosure is not a concern). Only score below 50 if comp is disclosed AND clearly below target."}

  culture_values      (0.15)  Score four signals (0–100 each), then average:
                                 autonomy_signal:     "own outcomes" vs "manage up"
                                 pace_signal:         "0→1 / scrappy" vs "process-driven"
                                 mission_signal:      explicit mission vs generic growth
                                 collaboration_model: embedded eng collab vs heavy XFN
                               Default each to 50 when absent (neutral, no penalty).
                               Compare against the candidate's stated company_types and aspirations.

  domain_background   (0.15)  How well does the candidate's background translate to this domain?
                               native(100) → adjacent(70) → tangential(40) → foreign(10).
                               Use extracted customer_type, product_surface, industry as signal.
                               IMPORTANT: score "foreign" ONLY when the role explicitly requires
                               domain-specific expertise the candidate clearly lacks — e.g. healthcare
                               regulatory, financial compliance, defense/gov clearance. A role in a
                               different industry than the candidate's target is NOT a reason to score
                               "foreign" by default. If industry_avoid is empty and the role has no
                               niche domain gatekeeping requirement, score adjacent(70) or above.
                               The candidate's strengths in AI/ML, developer tools, and B2B SaaS are
                               broadly transferable — presence of those strengths does NOT imply
                               "foreign" for roles outside their exact target industry.

  company_stage       (0.10)  Does the company stage match the candidate's stated preference?
                               Use extracted company_stage and company_tier.

MULTIPLIERS (apply to weighted score):
  overqualified: if inferred_structural_level is clearly below target level, apply
                 0.75 (seed) → 0.85 (series_b) → 0.95 (large company). Use company_stage.
  degree soft:   if degree_hard_requirement=true and candidate likely lacks it → 0.80×
  floor:         final_score ≥ weighted_score × 0.50 (two soft triggers never drop below half)

DEAL-BREAKER RULE (apply before scoring anything else):
  If a role clearly violates any item in the DEAL BREAKERS list above — based on the
  job title, company, industry, JD content, or extracted flags — set score=0,
  verdict="filtered", and add exactly one red tag naming the triggered rule
  (e.g., {{"text": "deal breaker: mgmt only", "sentiment": "red"}}).
  Set leveragePoints=[] and frictionPoints=[].
  A deal-breaker violation must NEVER produce verdict "apply", "consider", or "skipped".
  Also check: government_export_control=true, visa_sponsorship=false — flag if these
  conflict with candidate's situation.

STYLE:
  Use standard tech shorthands: ML, AI, API, infra, dev, eng, PM, SaaS, LLM, RAG, B2B, B2C, XFN.
  Lead PM = Staff PM — equivalent levels at most tech companies. NEVER flag "Lead" as a
  level concern or friction point. Only flag when the title is "Senior PM" or lower with
  no scope signal, or when the JD is clearly a manager-of-managers role below target.

Given a batch of job listings, return a JSON array — one object per job, same order as input:
[
  {{
    "score": <integer 0-100>,
    "verdict": "apply" | "consider" | "skipped" | "filtered",
    "dimensions": [
      {{"name": "seniority_scope",      "score": <0-100>, "rationale": "<≤12 words: specific evidence from JD vs candidate>"}},
      {{"name": "experience_relevance", "score": <0-100>, "rationale": "<≤12 words>"}},
      {{"name": "compensation_fit",     "score": <0-100>, "rationale": "<≤12 words>"}},
      {{"name": "culture_values",       "score": <0-100>, "rationale": "<≤12 words>"}},
      {{"name": "domain_background",    "score": <0-100>, "rationale": "<≤12 words>"}},
      {{"name": "company_stage",        "score": <0-100>, "rationale": "<≤12 words>"}}
    ],
    "leveragePoints": ["...", ...],
    "frictionPoints": ["..."],
    "tags": [
      {{"text": "...", "sentiment": "green" | "amber" | "red"}}
    ]
  }},
  ...
]

dimensions: always include all 6, in the order shown. rationale = one tight phrase citing
a specific JD fact or extracted field — no pronouns, no "the candidate", no banned words.
BAD: "The candidate has strong experience in this area."
GOOD: "8-yr AI platform track maps to required infra ownership scope."
For deal-breaker filtered roles, emit dimensions: [] (no scoring performed).

leveragePoints: exactly 2 bullets following the writing rules above. Always 2 — never 1, never 3.
frictionPoints: exactly 1 honest, specific concern following the writing rules above.
  Use [] only if there is genuinely no material concern at all.
  NEVER write placeholder text ("none", "n/a", "no concerns", "none material").
  For "skipped" verdict: frictionPoints[0] is shown as the skip reason in the digest.
    Write it as a short phrase (≤12 words). Always use JSON array syntax: ["phrase here"]
    BAD: ["The role is scoped as TPM, not PM — the candidate's career track is IC PM, making this misaligned regardless of company prestige."]
    GOOD: ["TPM role, not PM — title mismatch regardless of company prestige"]

TAG VOCABULARY — pick only from this list; do not invent new tags:

  GREEN (genuine match):
    "AI/ML: native"         "dev tools: match"        "enterprise SaaS: match"
    "stage: growth fit"     "stage: public co fit"     "level: Staff/Lead scope"
    "level: Principal scope" "0→1 scope"               "AI-native team"
    "strong eng collab"     "comp: meets floor"

  AMBER (caution — evaluate carefully):
    "domain: adjacent"      "domain: B2C gap"          "domain: hardware-adj"
    "level: scope unclear"  "level: title gap"         "level: overqualified"
    "stage: seed/early"     {"'comp: undisclosed'" if salary_is_hard_floor else "(comp:undisclosed — DO NOT USE: salary is aspirational, not a hard floor)"}        "visa: unclear"
    "degree gate"           "anon employer"

  RED (hard concerns):
    "domain: foreign"       {"'comp: below floor'" if salary_is_hard_floor else "(comp:below floor — DO NOT USE: salary is aspirational, not a hard floor)"}        "export ctrl flag"
    "clearance required"    "hard prereq: background"

  For deal-breaker filtered roles the gate code sets the tag automatically — do not add more.
  Use up to 4 tags. Pick the best match; do not combine two tags for the same dimension.

Thresholds (from the candidate's profile.yaml scoring section):
  score >= {apply_t}  →  apply
  score {consider_t}–{apply_t - 1}  →  consider
  score < {consider_t}   →  skipped
  deal_breaker violated  →  filtered (score=0, overrides all thresholds)

Be honest. {apply_t}% IS strong at this level. Do not inflate.
Return ONLY valid JSON array — no markdown fences, no preamble."""


def build_score_system(profile: dict) -> str:
    """Build the scoring system prompt from an already-loaded profile dict.

    Accepts the profile dict directly so the caller (pipeline) can pass the
    same object already loaded for gate checks — avoids a redundant disk read.

    Prompt ordering (via prompts.scoring_system_prompt):
      1. Identity (headhunter framing + evaluation standards)
      2. Candidate brief (synthesized orientation)
      3. Full rendered profile (detailed grounding)
      4. Calibration feedback (if any)
      5. Bullet writing rules
      6. Scoring rubric + output schema
    """
    from .profile import render_profile
    from .feedback import load_feedback_text
    from .prompts import scoring_system_prompt

    apply_t, consider_t = 75, 55
    sc = profile.get("scoring", {})
    try:
        apply_t    = int(sc.get("solid_match_threshold",   sc.get("apply_threshold",    apply_t)))
        consider_t = int(sc.get("moderate_match_threshold", sc.get("consider_threshold", consider_t)))
    except (TypeError, ValueError):
        pass

    name               = profile.get("candidate", {}).get("name") or _candidate_name()
    rendered           = render_profile(profile)
    bullet_guide       = _build_bullet_style_guide(profile)
    salary_is_hard_floor = bool(profile.get("salary_is_hard_floor", False))
    score_suffix       = _build_score_suffix(name, apply_t, consider_t, salary_is_hard_floor)
    feedback      = load_feedback_text()

    # Inject extracted-context instruction into bullet_guide preamble so it
    # stays co-located with the writing rules rather than floating loose.
    extracted_ctx_note = (
        "Each job listing includes an [EXTRACTED CONTEXT] block with structured fields "
        "extracted from the JD. Use these as grounding when scoring — they prevent misreads "
        "on salary, work model, seniority, and domain."
    )

    return scoring_system_prompt(
        profile=profile,
        rendered_profile=rendered,
        bullet_guide=extracted_ctx_note + "\n\n" + bullet_guide,
        score_suffix=score_suffix,
        feedback_text=feedback,
    )


def _build_score_system() -> str:
    """Legacy shim — loads profile from disk and delegates to build_score_system()."""
    from .profile import load_profile_yaml
    profile = load_profile_yaml()
    if not profile:
        raise FileNotFoundError(
            "No profile found at ~/.job_pipeline/profile.yaml\n"
            "Run `metis init` to create one from your resume."
        )
    return build_score_system(profile)


_SCORE_CHUNK_SIZE = 15   # max jobs per Sonnet call (~15 × 300 tok ≈ 4,500 out, fits in 8192)
_MAX_OUTPUT_TOKENS = 8192


def _score_chunk(client: anthropic.Anthropic, jobs: list[dict], system_prompt: str) -> list[dict]:
    """Score one chunk of jobs. Returns evals list (may be shorter than jobs on truncation)."""
    from .extract import format_extraction_for_scoring

    job_blocks = "\n\n---\n\n".join(
        "{header}\n{extraction}\n{jd_line}".format(
            header=f"JOB {i + 1}: {j['title']} at {j['company']} ({j['location']})",
            extraction=(
                "\n" + format_extraction_for_scoring(j.get("extraction", {}), listing_company=j.get("company", "")) + "\n"
                if j.get("extraction")
                else ""
            ),
            jd_line=(
                "JD:\n" + j["jd"][:1500]
                if j.get("jd")
                else "(No JD retrieved — score from title/company only)"
            ),
        )
        for i, j in enumerate(jobs)
    )

    _RETRYABLE = (
        anthropic.InternalServerError,   # 500 — transient server error
        anthropic.RateLimitError,        # 429
        anthropic.APIConnectionError,    # network blip
        anthropic.APITimeoutError,       # request timed out
    )
    _MAX_ATTEMPTS = 3
    response = None
    for attempt in range(_MAX_ATTEMPTS):
        try:
            response = client.messages.create(
                model=MODEL,
                max_tokens=_MAX_OUTPUT_TOKENS,
                system=[{"type": "text", "text": system_prompt, "cache_control": {"type": "ephemeral"}}],
                messages=[{
                    "role": "user",
                    "content": (
                        f"Score all {len(jobs)} jobs. "
                        f"Return a JSON array of exactly {len(jobs)} objects.\n\n"
                        f"{job_blocks}"
                    ),
                }],
            )
            break
        except _RETRYABLE as exc:
            if attempt < _MAX_ATTEMPTS - 1:
                wait = 2 ** attempt   # 1s, 2s
                log.warning(
                    "Scoring API error (attempt %d/%d): %s — retrying in %ds",
                    attempt + 1, _MAX_ATTEMPTS, exc, wait,
                )
                time.sleep(wait)
            else:
                log.error(
                    "Scoring API error after %d attempts: %s", _MAX_ATTEMPTS, exc
                )
                raise

    usage = response.usage
    log.info(
        "Scoring — input: %d tokens (cache_write: %d, cache_read: %d), output: %d tokens",
        usage.input_tokens,
        getattr(usage, "cache_creation_input_tokens", 0),
        getattr(usage, "cache_read_input_tokens", 0),
        usage.output_tokens,
    )

    raw = re.sub(
        r"^```(?:json)?\s*|\s*```$", "", response.content[0].text.strip(), flags=re.MULTILINE
    ).strip()
    try:
        evals = json.loads(raw)
        if isinstance(evals, dict):
            evals = [evals]
    except json.JSONDecodeError:
        evals = _recover_partial_json(raw)
        if evals:
            log.warning(
                "Chunk score JSON truncated — recovered %d/%d objects via partial parse",
                len(evals), len(jobs),
            )
        else:
            log.error(
                "Chunk score JSON parse failed entirely — %d jobs marked skipped.",
                len(jobs),
            )
    _inject_weights(evals)
    _normalize_list_fields(evals)
    return evals


def _normalize_list_fields(evals: list[dict]) -> None:
    """Coerce leveragePoints/frictionPoints to lists if Claude returned bare strings."""
    for ev in evals:
        for field in ("leveragePoints", "frictionPoints"):
            val = ev.get(field, [])
            if isinstance(val, str):
                ev[field] = [val.strip()] if val.strip() else []
            elif not isinstance(val, list):
                ev[field] = []


def _inject_weights(evals: list[dict]) -> None:
    """Enrich each eval's dimensions with weight and weighted_contribution (Python-owned values)."""
    for ev in evals:
        for dim in ev.get("dimensions", []):
            name = dim.get("name", "")
            w = WEIGHTS.get(name, 0.0)
            dim["weight"] = w
            dim["weighted_contribution"] = round(w * dim.get("score", 0), 1)


def score_jobs_batch(
    client: anthropic.Anthropic,
    jobs: list[dict],
    profile: dict | None = None,
) -> list[dict]:
    """Score all jobs, chunking into batches of _SCORE_CHUNK_SIZE to avoid output truncation.

    Pass `profile` (already loaded dict) to avoid a redundant disk read. Falls back to
    loading from disk when called without a profile (backward compat for tests).
    """
    system_prompt = build_score_system(profile) if profile is not None else _build_score_system()
    _error_eval   = {
        "score": 0, "verdict": "skipped",
        "leveragePoints": [], "frictionPoints": ["Scoring parse error"], "tags": [],
    }

    chunks = [jobs[i:i + _SCORE_CHUNK_SIZE] for i in range(0, len(jobs), _SCORE_CHUNK_SIZE)]
    if len(chunks) > 1:
        log.info("Scoring %d jobs in %d chunks of ≤%d", len(jobs), len(chunks), _SCORE_CHUNK_SIZE)

    all_evals: list[dict] = []
    for chunk in chunks:
        evals = _score_chunk(client, chunk, system_prompt)
        for i in range(len(chunk)):
            all_evals.append(evals[i] if i < len(evals) else _error_eval)

    for job, ev in zip(jobs, all_evals):
        job["eval"] = ev
    return jobs


def rank_jobs(jobs: list[dict]) -> list[dict]:
    """Sort jobs by verdict + score, re-deriving verdicts from thresholds first.

    Claude is instructed on thresholds but doesn't guarantee compliance —
    re-validating here ensures a score of 62 is never promoted to "apply".
    """
    apply_t, consider_t = 75, 55
    try:
        from .profile import load_profile_yaml
        sc = (load_profile_yaml() or {}).get("scoring", {})
        apply_t    = int(sc.get("solid_match_threshold",   sc.get("apply_threshold",    apply_t)))
        consider_t = int(sc.get("moderate_match_threshold", sc.get("consider_threshold", consider_t)))
    except Exception:
        pass

    for job in jobs:
        ev    = job.setdefault("eval", {})
        score = ev.get("score", 0)
        # "filtered" is set by Claude when a deal_breaker is violated — preserve it;
        # don't let a score of 0 accidentally demote it to "skipped".
        if ev.get("verdict") == "filtered":
            pass
        elif score >= apply_t:
            ev["verdict"] = "apply"
        elif score >= consider_t:
            ev["verdict"] = "consider"
        else:
            ev["verdict"] = "skipped"

    order = {"apply": 0, "consider": 1, "skipped": 2, "filtered": 3}
    return sorted(jobs, key=lambda j: (
        order.get(j["eval"].get("verdict", "skipped"), 3),
        -j["eval"].get("score", 0),
    ))
