"""Profile loader — reads profile.yaml and renders it into a scoring prompt block.

Priority order:
  1. ~/.job_pipeline/profile.yaml  (structured YAML — generated by `scorerole init`)
  2. ~/.job_pipeline/profile.md    (legacy free-text — still supported)
  3. Inline fallback stub           (last resort, not used in practice)
"""
import logging
from pathlib import Path

log = logging.getLogger(__name__)

PROFILE_DIR  = Path.home() / ".job_pipeline"
YAML_PATH    = PROFILE_DIR / "profile.yaml"
MD_PATH      = PROFILE_DIR / "profile.md"


# ---------------------------------------------------------------------------
# YAML loader + renderer
# ---------------------------------------------------------------------------

def load_profile_yaml() -> dict | None:
    """Return the profile dict if profile.yaml exists and parses cleanly."""
    if not YAML_PATH.exists():
        return None
    try:
        import yaml  # pyyaml — installed via requirements
        data = yaml.safe_load(YAML_PATH.read_text())
        log.info(f"Loaded profile from {YAML_PATH}")
        return data
    except Exception as e:
        log.warning(f"Failed to parse {YAML_PATH}: {e}")
        return None


def render_profile(data: dict) -> str:
    """Convert a profile.yaml dict into a human-readable scoring prompt block."""
    c  = data.get("candidate", {})
    t  = data.get("target", {})
    sc = data.get("scoring", {})

    name     = c.get("name", "Candidate")
    location = c.get("location", "")

    # Work mode: prefer the stored list (set by wizard); fall back to bool
    work_mode_list = c.get("work_mode") or []
    if work_mode_list:
        remote = ", ".join(work_mode_list)
    elif c.get("open_to_remote"):
        remote = "remote-friendly"
    else:
        remote = "on-site preferred"

    reloc      = ", ".join(c.get("open_to_relocation", []))
    level      = t.get("level", "")
    roles      = ", ".join(t.get("roles", []))
    industries = ", ".join(t.get("industries", []))

    apply_t    = sc.get("apply_threshold", 75)
    consider_t = sc.get("consider_threshold", 55)
    deduction  = sc.get("level_mismatch_deduction", 10)

    lines = [
        f"CANDIDATE: {name} — actively searching",
        f"TARGET LEVEL: {level} — {roles}",
        f"LOCATION: {location}; {remote}",
    ]
    if reloc:
        lines.append(f"OPEN TO RELOCATION: {reloc}")
    if industries:
        lines.append(f"PREFERRED INDUSTRIES: {industries}")

    # Aspirations — track, direction, company types
    asp = data.get("aspirations", {})
    if asp:
        lines += ["", "ASPIRATIONS:"]
        if asp.get("track"):
            lines.append(f"Track: {asp['track']}")
        if asp.get("direction"):
            lines.append(asp["direction"].strip())
        if asp.get("company_types"):
            lines.append(f"Drawn to: {', '.join(asp['company_types'])}")
        if asp.get("avoid_company_types"):
            lines.append(f"Avoid company types: {', '.join(asp['avoid_company_types'])}")

    # Soft preferences — stage, industry nudges, aspirational salary
    pref = data.get("preferences", {})
    if pref:
        lines += ["", "PREFERENCES (soft signals — nudge ranking, don't disqualify):"]
        if pref.get("company_stage"):
            lines.append(f"Stage preference: {', '.join(pref['company_stage'])}")
        if pref.get("industry_targets"):
            lines.append(f"Move toward: {', '.join(pref['industry_targets'])}")
        if pref.get("industry_avoid"):
            lines.append(f"Steer away from: {', '.join(pref['industry_avoid'])}")
        if pref.get("base_salary_target_usd"):
            lines.append(f"Target base salary: ${pref['base_salary_target_usd']:,}")

    lines += [
        "",
        "SCORE CALIBRATION:",
        f"Apply threshold: {apply_t}+.  Consider: {consider_t}+.",
        f"If title lacks Staff / Lead / Principal / Director / Head / VP / GM, "
        f"deduct {deduction} points — it's a lateral or downward move.",
    ]

    if data.get("notes"):
        lines += ["", data["notes"].strip()]

    exp = data.get("experience", [])
    if exp:
        lines += ["", "EXPERIENCE:"]
        for e in exp:
            lines.append(
                f"- {e.get('company', '')}: {e.get('title', '')} ({e.get('dates', '')})"
            )
            for h in e.get("highlights", []):
                lines.append(f"    • {h}")

    edu = data.get("education", [])
    if edu:
        lines += ["", "EDUCATION:"]
        for e in edu:
            inst = e.get("institution") or ""
            deg  = e.get("degree", "")
            yr   = e.get("year")
            entry = f"- {deg}"
            if inst:
                entry += f" — {inst}"
            if yr:
                entry += f" ({yr})"
            lines.append(entry)

    strengths = data.get("strengths", [])
    if strengths:
        lines += ["", "CORE STRENGTHS:"]
        lines += [f"- {s}" for s in strengths]

    for key, label in [
        ("green_flags",  "GREEN FLAGS"),
        ("yellow_flags", "YELLOW FLAGS"),
        ("red_flags",    "RED FLAGS"),
    ]:
        flags = data.get(key, [])
        if flags:
            lines.append(f"\n{label}: {'; '.join(flags)}")

    if data.get("deal_breakers"):
        lines.append(f"\nDEAL BREAKERS: {', '.join(data['deal_breakers'])}")

    if data.get("salary_floor_usd"):
        lines.append(f"\nSALARY FLOOR: ${data['salary_floor_usd']:,}")

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Unified loader — called by score.py
# ---------------------------------------------------------------------------

def load_profile_text() -> str | None:
    """Return profile as a prompt-ready string, or None if nothing found.

    Tries YAML first (structured, generated by scorerole init), then
    falls back to the legacy free-text profile.md.
    """
    # 1. YAML (preferred)
    data = load_profile_yaml()
    if data:
        return render_profile(data)

    # 2. Legacy markdown
    if MD_PATH.exists():
        content = MD_PATH.read_text().strip()
        if content:
            log.info(f"Loaded profile from {MD_PATH} (legacy)")
            return content

    return None
