import re, json, logging, time
from pathlib import Path
import anthropic

log = logging.getLogger(__name__)

# MODEL is read from pipeline.py at call time — passed in via the client object.
# Keep a local reference for the score_jobs_batch call.
import os
MODEL           = os.getenv("MODEL",           "claude-sonnet-4-6")
PRESCREEN_MODEL = os.getenv("PRESCREEN_MODEL", "claude-haiku-4-5")

# ---------------------------------------------------------------------------
# Profile — priority order:
#   1. ~/.job_pipeline/profile.yaml  (structured; generated by `scorerole init`)
#   2. ~/.job_pipeline/profile.md    (legacy free-text; still supported)
#
# No profile found → hard error pointing to `scorerole init`.
# ---------------------------------------------------------------------------

def _load_profile() -> str:
    from .profile import load_profile_text
    text = load_profile_text()
    if text:
        return text
    raise FileNotFoundError(
        "No profile found at ~/.job_pipeline/profile.yaml\n"
        "Run `scorerole init` to create one from your resume."
    )


def _candidate_name() -> str:
    """Extract candidate name from profile.yaml, or return generic fallback."""
    try:
        from .profile import load_profile_yaml
        data = load_profile_yaml()
        if data:
            return data.get("candidate", {}).get("name", "the candidate")
    except Exception:
        pass
    return "the candidate"


# ---------------------------------------------------------------------------
# Pre-screen — fast Haiku pass on title+company only (no JD fetch)
# ---------------------------------------------------------------------------

def _build_prescreen_context() -> str:
    """Minimal profile context for pre-screening.

    Intentionally excludes seniority level and target role titles — the pre-screen
    only sees title+company (no JD), so it cannot reliably assess scope. A "Senior PM"
    role may be staff-scope in practice; filtering on level here causes false negatives.
    Only deal-breakers that are inferable from title+company alone are included.
    """
    try:
        from .profile import load_profile_yaml
        data = load_profile_yaml() or {}
    except Exception:
        return ""

    target_roles = data.get("target", {}).get("roles", [])
    # Use first target role as the function signal; fall back to PM for legacy profiles.
    function_hint = target_roles[0] if target_roles else "Product Management"
    lines: list[str] = [
        f"Candidate is seeking: {function_hint} (and similar roles at same level).",
        "Filter ONLY if the role is a completely different function "
        "(e.g., candidate seeks ML Engineering but role is Marketing or Finance).",
    ]

    deal_breakers = data.get("deal_breakers", [])
    if deal_breakers:
        lines.append("Hard no (flag if obviously matched by title/company): "
                     + "; ".join(str(d) for d in deal_breakers[:6]))

    return "\n".join(lines)


def estimate_cost(n: int) -> str:
    """Human-readable Sonnet cost range for scoring n jobs (upper bound before pre-screen).

    Exported so pipeline.py can reference this single source of truth for cost estimates.
    """
    lo, hi = n * 0.005, n * 0.015
    return f"${lo:.2f}–${hi:.2f}"


def _recover_partial_json(raw: str) -> list[dict]:
    """Salvage individual job objects from a truncated JSON array.

    Walks the raw string tracking brace depth so each complete {...} block
    can be parsed independently, returning whatever objects are valid.
    """
    objects: list[dict] = []
    depth, start = 0, None
    for i, ch in enumerate(raw):
        if ch == "{":
            if depth == 0:
                start = i
            depth += 1
        elif ch == "}":
            depth -= 1
            if depth == 0 and start is not None:
                try:
                    obj = json.loads(raw[start : i + 1])
                    if isinstance(obj, dict):
                        objects.append(obj)
                except json.JSONDecodeError:
                    pass
                start = None
    return objects


def prescreen_jobs_batch(client: anthropic.Anthropic, jobs: list[dict]) -> list[dict]:
    """Fast Haiku pre-screen on title+company only — filters obvious mismatches before
    JD enrichment and full Sonnet scoring.

    Returns the subset of jobs worth scoring.  Falls back to the full list if
    the API call fails or the response cannot be parsed.
    """
    if not jobs:
        return jobs

    context = _build_prescreen_context()
    if not context:
        log.warning("Pre-screen: no profile context — skipping filter")
        return jobs

    job_lines = "\n".join(
        f"{i + 1}. {j['title']} at {j['company']}"
        for i, j in enumerate(jobs)
    )

    try:
        response = client.messages.create(
            model=PRESCREEN_MODEL,
            max_tokens=max(256, len(jobs) * 12),  # ~12 tok/job: "1. Y\n" with headroom
            system=(
                f"{context}\n\n"
                "Quick function filter. For each numbered job output only the number "
                "and Y or N — nothing else.\n"
                "N = wrong function entirely: engineering, design, marketing, sales, "
                "data science, finance, operations, or legal role — NOT a PM/product role. "
                "OR the title+company obviously matches a hard-no deal-breaker above.\n"
                "Y = everything else, including all seniority levels of PM/product roles "
                "(IC, Senior, Lead, Staff, Principal, Director, VP). "
                "Never filter on seniority — scope must be assessed from the JD, not the title.\n"
                "When uncertain, Y."
            ),
            messages=[{"role": "user", "content": job_lines}],
        )
    except Exception as exc:
        log.warning(
            "Pre-screen API call failed (%s) — skipping filter, proceeding with all %d roles. "
            "Estimated Sonnet cost: ~$%.4f",
            exc, len(jobs), estimate_cost(len(jobs)),
        )
        return jobs

    raw   = response.content[0].text.strip()
    usage = response.usage
    log.info(
        f"Pre-screen ({PRESCREEN_MODEL}) — "
        f"input: {usage.input_tokens} tok, output: {usage.output_tokens} tok"
    )

    # Parse lines like "1. Y", "2. N", "3 Y", "4) N", etc.
    passed:   list[dict] = []
    filtered: list[str]  = []
    matched:  set[int]   = set()
    for line in raw.splitlines():
        m = re.match(r"(\d+)[.):\s]+([YN])", line.strip(), re.IGNORECASE)
        if m:
            idx     = int(m.group(1)) - 1
            verdict = m.group(2).upper()
            if 0 <= idx < len(jobs) and idx not in matched:
                matched.add(idx)
                if verdict == "Y":
                    passed.append(jobs[idx])
                else:
                    filtered.append(f"{jobs[idx]['title']} at {jobs[idx]['company']}")

    if not passed and not filtered:
        log.warning(
            "Pre-screen: response couldn't be parsed — proceeding with all %d roles. "
            "Estimated Sonnet cost: ~$%.4f",
            len(jobs), estimate_cost(len(jobs)),
        )
        return jobs

    log.info("Pre-screen: %d/%d passed (%d filtered out)", len(passed), len(jobs), len(filtered))
    if filtered:
        log.info("Pre-screen filtered:\n  " + "\n  ".join(filtered))
    return passed


# ---------------------------------------------------------------------------
# Full scoring (Sonnet)
# ---------------------------------------------------------------------------

def _build_score_system() -> str:
    """Build the scoring system prompt, loading the profile fresh each call."""
    profile = _load_profile()
    name = _candidate_name()

    # Read scoring thresholds from profile.yaml; fall back to safe defaults.
    apply_t, consider_t = 75, 55
    try:
        from .profile import load_profile_yaml
        sc = (load_profile_yaml() or {}).get("scoring", {})
        apply_t    = int(sc.get("apply_threshold",    apply_t))
        consider_t = int(sc.get("consider_threshold", consider_t))
    except Exception:
        pass

    return f"""{profile}

You are a job fit evaluator for {name}.

Each job listing includes an [EXTRACTED CONTEXT] block with structured fields extracted
from the JD. Use these as grounding when scoring — they prevent misreads on salary,
work model, seniority, and domain.

SCORING RUBRIC — score six dimensions (0–100 each), then compute weighted total:

  seniority_scope     (0.25)  Does the scope, ownership language, and structural level
                               match {name}'s target level? Use extracted inferred_structural_level,
                               manages_pm_team, reports_to_level as anchors.

  experience_relevance (0.20)  How well does the JD's required stack and depth match
                               {name}'s background? Target 70–80% match: 100% overlap
                               scores ~85 (no growth headroom), not 100.

  compensation_fit    (0.15)  Does total comp land attractively above the salary floor?
                               If salary_disclosed=false, cap this dimension at 60 (can't assess).

  culture_values      (0.15)  Score these four signals (0–100 each), then average:
                                 autonomy_signal:     "own outcomes" vs "manage up"
                                 pace_signal:         "0→1 / scrappy" vs "process-driven"
                                 mission_signal:      explicit mission vs generic growth
                                 collaboration_model: embedded eng collab vs heavy XFN
                               Default each to 50 when absent (neutral, no penalty).
                               Compare against candidate's stated company_types and aspirations.

  domain_background   (0.15)  How native is {name}'s background to this domain?
                               native(100) → adjacent(70) → tangential(40) → foreign(10).
                               Use extracted customer_type, product_surface, industry as signal.

  company_stage       (0.10)  Does the company stage match candidate's stated preference?
                               Use extracted company_stage and company_tier.

MULTIPLIERS (apply to weighted score):
  overqualified: if inferred_structural_level is clearly below target level, apply
                 0.75 (seed) → 0.85 (series_b) → 0.95 (large company). Use company_stage.
  degree soft:   if degree_hard_requirement=true and candidate likely lacks it → 0.80×
  floor:         final_score ≥ weighted_score × 0.50 (two soft triggers never drop below half)

DEAL-BREAKER RULE (apply before scoring anything else):
  If a role clearly violates any item in the DEAL BREAKERS list above — based on the
  job title, company, industry, JD content, or extracted flags — set score=0,
  verdict="filtered", and add exactly one red tag naming the triggered rule
  (e.g., {{"text": "deal breaker: mgmt only", "sentiment": "red"}}).
  Set leveragePoints=[] and frictionPoints=[].
  A deal-breaker violation must NEVER produce verdict "apply", "consider", or "skipped".
  Also check: government_export_control=true, visa_sponsorship=false — flag if these
  conflict with candidate's situation.

STYLE:
  Use standard tech shorthands: ML, AI, API, infra, dev, eng, PM, SaaS, LLM, RAG, B2B, B2C, XFN.
  Lead PM = Staff PM — these are equivalent levels at most tech companies. NEVER flag "Lead"
  as a level concern, title gap, or friction point. Only flag when the title is "Senior PM"
  or lower with no scope signal, or when the JD is clearly a manager-of-managers role below target.
  NEVER mention score adjustments, multipliers, deductions, or any numerical scoring mechanics
  in leveragePoints, frictionPoints, or tags — those are internal. Write only real-world job factors.

Given a batch of job listings, return a JSON array — one object per job, same order as input:
[
  {{
    "score": <integer 0-100>,
    "verdict": "apply" | "consider" | "skipped" | "filtered",
    "leveragePoints": ["...", ...],
    "frictionPoints": ["..."],
    "tags": [
      {{"text": "...", "sentiment": "green" | "amber" | "red"}}
    ]
  }},
  ...
]

leveragePoints: 1-2 complete, natural sentences. ~15-20 words each. Explain why this role
  is a strong fit — name the specific skill or experience and tie it to something concrete
  in the JD. Write like you're telling a colleague why this role is interesting, not filling
  in a template. Avoid mechanical openers ("maps directly to", "aligns with") and avoid the
  stiff "topic label — evidence clause" em-dash pattern.
  BAD:  "agentic platform — DocuSign Navigator flows map directly to JD's core workflow need"
  GOOD: "DocuSign Navigator's agentic platform work is a direct match for the JD's focus on
         autonomous workflow orchestration at enterprise scale."

frictionPoints: 1 honest, specific concern in the same natural-sentence style. Use [] if
  there is genuinely no material concern — never write placeholder text ("none", "n/a",
  "no concerns", "none material").
  BAD:  "none material"
  GOOD: []

TAG VOCABULARY — pick only from this list; do not invent new tags:

  GREEN (genuine match):
    "AI/ML: native"         "dev tools: match"        "enterprise SaaS: match"
    "stage: growth fit"     "stage: public co fit"     "level: Staff/Lead scope"
    "level: Principal scope" "0→1 scope"               "AI-native team"
    "strong eng collab"     "comp: meets floor"

  AMBER (caution — evaluate carefully):
    "domain: adjacent"      "domain: B2C gap"          "domain: hardware-adj"
    "level: scope unclear"  "level: title gap"         "level: overqualified"
    "stage: seed/early"     "comp: undisclosed"        "visa: unclear"
    "degree gate"           "anon employer"

  RED (hard concerns):
    "domain: foreign"       "comp: below floor"        "export ctrl flag"
    "clearance required"    "hard prereq: background"

  For deal-breaker filtered roles the gate code sets the tag automatically — do not add more.
  Use up to 4 tags. Pick the best match; do not combine two tags for the same dimension.

Thresholds (from your profile.yaml scoring section):
  score >= {apply_t}  →  apply
  score {consider_t}–{apply_t - 1}  →  consider
  score < {consider_t}   →  skipped
  deal_breaker violated  →  filtered (score=0, overrides all thresholds)

Be honest. {apply_t}% IS strong at this level. Do not inflate.
Return ONLY valid JSON array — no markdown fences, no preamble."""


_SCORE_CHUNK_SIZE = 15   # max jobs per Sonnet call (~15 × 300 tok ≈ 4,500 out, fits in 8192)
_MAX_OUTPUT_TOKENS = 8192


def _score_chunk(client: anthropic.Anthropic, jobs: list[dict], system_prompt: str) -> list[dict]:
    """Score one chunk of jobs. Returns evals list (may be shorter than jobs on truncation)."""
    from .extract import format_extraction_for_scoring

    job_blocks = "\n\n---\n\n".join(
        "{header}\n{extraction}\n{jd_line}".format(
            header=f"JOB {i + 1}: {j['title']} at {j['company']} ({j['location']})",
            extraction=(
                "\n" + format_extraction_for_scoring(j.get("extraction", {})) + "\n"
                if j.get("extraction")
                else ""
            ),
            jd_line=(
                "JD:\n" + j["jd"][:1500]
                if j.get("jd")
                else "(No JD retrieved — score from title/company only)"
            ),
        )
        for i, j in enumerate(jobs)
    )

    _RETRYABLE = (
        anthropic.InternalServerError,   # 500 — transient server error
        anthropic.RateLimitError,        # 429
        anthropic.APIConnectionError,    # network blip
        anthropic.APITimeoutError,       # request timed out
    )
    _MAX_ATTEMPTS = 3
    response = None
    for attempt in range(_MAX_ATTEMPTS):
        try:
            response = client.messages.create(
                model=MODEL,
                max_tokens=_MAX_OUTPUT_TOKENS,
                system=[{"type": "text", "text": system_prompt, "cache_control": {"type": "ephemeral"}}],
                messages=[{
                    "role": "user",
                    "content": (
                        f"Score all {len(jobs)} jobs. "
                        f"Return a JSON array of exactly {len(jobs)} objects.\n\n"
                        f"{job_blocks}"
                    ),
                }],
            )
            break
        except _RETRYABLE as exc:
            if attempt < _MAX_ATTEMPTS - 1:
                wait = 2 ** attempt   # 1s, 2s
                log.warning(
                    "Scoring API error (attempt %d/%d): %s — retrying in %ds",
                    attempt + 1, _MAX_ATTEMPTS, exc, wait,
                )
                time.sleep(wait)
            else:
                log.error(
                    "Scoring API error after %d attempts: %s", _MAX_ATTEMPTS, exc
                )
                raise

    usage = response.usage
    log.info(
        "Scoring — input: %d tokens (cache_write: %d, cache_read: %d), output: %d tokens",
        usage.input_tokens,
        getattr(usage, "cache_creation_input_tokens", 0),
        getattr(usage, "cache_read_input_tokens", 0),
        usage.output_tokens,
    )

    raw = re.sub(
        r"^```(?:json)?\s*|\s*```$", "", response.content[0].text.strip(), flags=re.MULTILINE
    ).strip()
    try:
        evals = json.loads(raw)
        if isinstance(evals, dict):
            evals = [evals]
        return evals
    except json.JSONDecodeError:
        evals = _recover_partial_json(raw)
        if evals:
            log.warning(
                "Chunk score JSON truncated — recovered %d/%d objects via partial parse",
                len(evals), len(jobs),
            )
        else:
            log.error(
                "Chunk score JSON parse failed entirely — %d jobs marked skipped.",
                len(jobs),
            )
        return evals


def score_jobs_batch(client: anthropic.Anthropic, jobs: list[dict]) -> list[dict]:
    """Score all jobs, chunking into batches of _SCORE_CHUNK_SIZE to avoid output truncation."""
    system_prompt = _build_score_system()
    _error_eval   = {
        "score": 0, "verdict": "skipped",
        "leveragePoints": [], "frictionPoints": ["Scoring parse error"], "tags": [],
    }

    chunks = [jobs[i:i + _SCORE_CHUNK_SIZE] for i in range(0, len(jobs), _SCORE_CHUNK_SIZE)]
    if len(chunks) > 1:
        log.info("Scoring %d jobs in %d chunks of ≤%d", len(jobs), len(chunks), _SCORE_CHUNK_SIZE)

    all_evals: list[dict] = []
    for chunk in chunks:
        evals = _score_chunk(client, chunk, system_prompt)
        for i in range(len(chunk)):
            all_evals.append(evals[i] if i < len(evals) else _error_eval)

    for job, ev in zip(jobs, all_evals):
        job["eval"] = ev
    return jobs


def rank_jobs(jobs: list[dict]) -> list[dict]:
    """Sort jobs by verdict + score, re-deriving verdicts from thresholds first.

    Claude is instructed on thresholds but doesn't guarantee compliance —
    re-validating here ensures a score of 62 is never promoted to "apply".
    """
    apply_t, consider_t = 75, 55
    try:
        from .profile import load_profile_yaml
        sc = (load_profile_yaml() or {}).get("scoring", {})
        apply_t    = int(sc.get("apply_threshold",    apply_t))
        consider_t = int(sc.get("consider_threshold", consider_t))
    except Exception:
        pass

    for job in jobs:
        ev    = job.setdefault("eval", {})
        score = ev.get("score", 0)
        # "filtered" is set by Claude when a deal_breaker is violated — preserve it;
        # don't let a score of 0 accidentally demote it to "skipped".
        if ev.get("verdict") == "filtered":
            pass
        elif score >= apply_t:
            ev["verdict"] = "apply"
        elif score >= consider_t:
            ev["verdict"] = "consider"
        else:
            ev["verdict"] = "skipped"

    order = {"apply": 0, "consider": 1, "skipped": 2, "filtered": 3}
    return sorted(jobs, key=lambda j: (
        order.get(j["eval"].get("verdict", "skipped"), 3),
        -j["eval"].get("score", 0),
    ))
