import re, json, logging
from pathlib import Path
import anthropic

log = logging.getLogger(__name__)

# MODEL is read from pipeline.py at call time — passed in via the client object.
# Keep a local reference for the score_jobs_batch call.
import os
MODEL = os.getenv("MODEL", "claude-sonnet-4-6")

# ---------------------------------------------------------------------------
# Profile — priority order:
#   1. ~/.job_pipeline/profile.yaml  (structured; generated by `scorerole init`)
#   2. ~/.job_pipeline/profile.md    (legacy free-text; still supported)
#
# No profile found → hard error pointing to `scorerole init`.
# ---------------------------------------------------------------------------

def _load_profile() -> str:
    from .profile import load_profile_text
    text = load_profile_text()
    if text:
        return text
    raise FileNotFoundError(
        "No profile found at ~/.job_pipeline/profile.yaml\n"
        "Run `scorerole init` to create one from your resume."
    )


def _candidate_name() -> str:
    """Extract candidate name from profile.yaml, or return generic fallback."""
    try:
        from .profile import load_profile_yaml
        data = load_profile_yaml()
        if data:
            return data.get("candidate", {}).get("name", "the candidate")
    except Exception:
        pass
    return "the candidate"


def _build_score_system() -> str:
    """Build the scoring system prompt, loading the profile fresh each call."""
    profile = _load_profile()
    name = _candidate_name()

    # Read scoring thresholds from profile.yaml; fall back to safe defaults.
    apply_t, consider_t = 75, 55
    try:
        from .profile import load_profile_yaml
        sc = (load_profile_yaml() or {}).get("scoring", {})
        apply_t    = int(sc.get("apply_threshold",    apply_t))
        consider_t = int(sc.get("consider_threshold", consider_t))
    except Exception:
        pass

    return f"""{profile}

You are a job fit evaluator for {name}.

Given a batch of job listings, return a JSON array — one object per job, same order as input:
[
  {{
    "score": <integer 0-100>,
    "verdict": "apply" | "consider" | "skipped",
    "leveragePoints": ["<short phrase ≤5 words>", ...],
    "frictionPoints": ["<short phrase ≤5 words>", ...],
    "tags": [
      {{"text": "<≤5 words>", "sentiment": "green" | "amber" | "red"}}
    ]
  }},
  ...
]

leveragePoints: 1-2 match explanations. Lead with a 2-4 word topic label, em-dash (—), then a
  tight evidence clause. ~12 words total. No "JD needs" prefix — write naturally.
  BAD:  "JD needs agentic workflow design → DocuSign Navigator agentic flows"
  GOOD: "agentic platform — DocuSign Navigator flows match JD's core workflow need"
  BAD:  "JD wants ML depth → UIUC + model eval"
  GOOD: "ML depth — UIUC Deep Learning for Healthcare + 2k-model eval fits JD"
  BAD:  "0-1 PRD authoring"
  GOOD: "0-1 build — DocuSign Custom Extractions built from zero matches JD scope"

frictionPoints: 1 honest concern, same format. Use [] if no real friction.
  NEVER write placeholder text ("none", "n/a", "none material", "no concerns", etc.).
  BAD:  "none material"
  GOOD: []
  BAD:  "JD expects crawl/index infra exp → no direct background"
  GOOD: "crawl/index infra — no direct background, though ML systems work overlaps"

tags: Up to 4 highlight tags. "green" = clear JD↔background match, "amber" = caution or
      domain gap, "red" = hard blocker. ≤5 words each.

Thresholds (from your profile.yaml scoring section):
  score >= {apply_t}  →  apply
  score {consider_t}–{apply_t - 1}  →  consider
  score < {consider_t}   →  skipped

Be honest. {apply_t}% IS strong at this level. Do not inflate.
Return ONLY valid JSON array — no markdown fences, no preamble."""


def score_jobs_batch(client: anthropic.Anthropic, jobs: list[dict]) -> list[dict]:
    job_blocks = "\n\n---\n\n".join(
        "JOB {n}: {title} at {company} ({location})\n{jd_line}".format(
            n=i + 1,
            title=j["title"],
            company=j["company"],
            location=j["location"],
            jd_line=(
                "JD:\n" + j["jd"][:1500]
                if j.get("jd")
                else "(No JD retrieved — score from title/company only)"
            ),
        )
        for i, j in enumerate(jobs)
    )

    response = client.messages.create(
        model=MODEL,
        max_tokens=4096,
        system=[
            {
                "type": "text",
                "text": _build_score_system(),
                "cache_control": {"type": "ephemeral"},
            }
        ],
        messages=[{
            "role": "user",
            "content": (
                f"Score all {len(jobs)} jobs. "
                f"Return a JSON array of exactly {len(jobs)} objects.\n\n"
                f"{job_blocks}"
            ),
        }],
    )

    usage = response.usage
    log.info(
        f"Scoring — input: {usage.input_tokens} tokens "
        f"(cache_write: {getattr(usage, 'cache_creation_input_tokens', 0)}, "
        f"cache_read: {getattr(usage, 'cache_read_input_tokens', 0)}), "
        f"output: {usage.output_tokens} tokens"
    )

    raw = re.sub(
        r"^```(?:json)?\s*|\s*```$", "", response.content[0].text.strip(), flags=re.MULTILINE
    ).strip()
    try:
        evals = json.loads(raw)
        if isinstance(evals, dict):
            evals = [evals]
    except json.JSONDecodeError:
        log.warning("Batch score JSON parse failed — all jobs marked skip")
        evals = []

    for i, job in enumerate(jobs):
        job["eval"] = evals[i] if i < len(evals) else {
            "score": 0, "verdict": "skipped", "leveragePoints": [], "frictionPoints": ["Scoring parse error"], "tags": []
        }
    return jobs


def rank_jobs(jobs: list[dict]) -> list[dict]:
    """Sort jobs by verdict + score, re-deriving verdicts from thresholds first.

    Claude is instructed on thresholds but doesn't guarantee compliance —
    re-validating here ensures a score of 62 is never promoted to "apply".
    """
    apply_t, consider_t = 75, 55
    try:
        from .profile import load_profile_yaml
        sc = (load_profile_yaml() or {}).get("scoring", {})
        apply_t    = int(sc.get("apply_threshold",    apply_t))
        consider_t = int(sc.get("consider_threshold", consider_t))
    except Exception:
        pass

    for job in jobs:
        ev    = job.setdefault("eval", {})
        score = ev.get("score", 0)
        if score >= apply_t:
            ev["verdict"] = "apply"
        elif score >= consider_t:
            ev["verdict"] = "consider"
        else:
            ev["verdict"] = "skipped"

    order = {"apply": 0, "consider": 1, "skipped": 2}
    return sorted(jobs, key=lambda j: (
        order.get(j["eval"].get("verdict", "skipped"), 3),
        -j["eval"].get("score", 0),
    ))
