import re, json, logging
from pathlib import Path
import anthropic

log = logging.getLogger(__name__)

# MODEL is read from pipeline.py at call time — passed in via the client object.
# Keep a local reference for the score_jobs_batch call.
import os
MODEL           = os.getenv("MODEL",           "claude-sonnet-4-6")
PRESCREEN_MODEL = os.getenv("PRESCREEN_MODEL", "claude-haiku-4-5")

# ---------------------------------------------------------------------------
# Profile — priority order:
#   1. ~/.job_pipeline/profile.yaml  (structured; generated by `scorerole init`)
#   2. ~/.job_pipeline/profile.md    (legacy free-text; still supported)
#
# No profile found → hard error pointing to `scorerole init`.
# ---------------------------------------------------------------------------

def _load_profile() -> str:
    from .profile import load_profile_text
    text = load_profile_text()
    if text:
        return text
    raise FileNotFoundError(
        "No profile found at ~/.job_pipeline/profile.yaml\n"
        "Run `scorerole init` to create one from your resume."
    )


def _candidate_name() -> str:
    """Extract candidate name from profile.yaml, or return generic fallback."""
    try:
        from .profile import load_profile_yaml
        data = load_profile_yaml()
        if data:
            return data.get("candidate", {}).get("name", "the candidate")
    except Exception:
        pass
    return "the candidate"


# ---------------------------------------------------------------------------
# Pre-screen — fast Haiku pass on title+company only (no JD fetch)
# ---------------------------------------------------------------------------

def _build_prescreen_context() -> str:
    """Condensed profile snapshot for pre-screening — targeting criteria only."""
    try:
        from .profile import load_profile_yaml
        data = load_profile_yaml() or {}
    except Exception:
        return ""

    lines: list[str] = []
    cand   = data.get("candidate", {})
    target = data.get("target",    {})

    name, title = cand.get("name", ""), cand.get("title", "")
    parts = [p for p in [name, title] if p]
    if parts:
        lines.append("Candidate: " + ", ".join(parts))

    roles = target.get("roles", [])
    if roles:
        lines.append("Targeting: " + ", ".join(roles))

    level = cand.get("seniority", "") or target.get("level", "")
    if level:
        lines.append(f"Seniority: {level}")

    deal_breakers = data.get("deal_breakers", [])
    if deal_breakers:
        lines.append("Hard no: " + "; ".join(str(d) for d in deal_breakers[:4]))

    return "\n".join(lines)


def _estimate_sonnet_cost(jobs: list[dict]) -> float:
    """Rough upper-bound cost estimate for scoring n jobs with Sonnet."""
    return len(jobs) * 0.015


def _recover_partial_json(raw: str) -> list[dict]:
    """Salvage individual job objects from a truncated JSON array.

    Walks the raw string tracking brace depth so each complete {...} block
    can be parsed independently, returning whatever objects are valid.
    """
    objects: list[dict] = []
    depth, start = 0, None
    for i, ch in enumerate(raw):
        if ch == "{":
            if depth == 0:
                start = i
            depth += 1
        elif ch == "}":
            depth -= 1
            if depth == 0 and start is not None:
                try:
                    obj = json.loads(raw[start : i + 1])
                    if isinstance(obj, dict):
                        objects.append(obj)
                except json.JSONDecodeError:
                    pass
                start = None
    return objects


def prescreen_jobs_batch(client: anthropic.Anthropic, jobs: list[dict]) -> list[dict]:
    """Fast Haiku pre-screen on title+company only — filters obvious mismatches before
    JD enrichment and full Sonnet scoring.

    Returns the subset of jobs worth scoring.  Falls back to the full list if
    the API call fails or the response cannot be parsed.
    """
    if not jobs:
        return jobs

    context = _build_prescreen_context()
    if not context:
        log.warning("Pre-screen: no profile context — skipping filter")
        return jobs

    job_lines = "\n".join(
        f"{i + 1}. {j['title']} at {j['company']}"
        for i, j in enumerate(jobs)
    )

    try:
        response = client.messages.create(
            model=PRESCREEN_MODEL,
            max_tokens=max(128, len(jobs) * 8),
            system=(
                f"{context}\n\n"
                "Quick relevance filter. For each numbered job output only the number "
                "and Y or N — nothing else.\n"
                "Y = plausibly relevant to this candidate's targets and background.\n"
                "N = clear mismatch (wrong function, obviously wrong seniority, "
                "or matches a hard-no rule).\n"
                "When uncertain, say Y."
            ),
            messages=[{"role": "user", "content": job_lines}],
        )
    except Exception as exc:
        log.warning(
            "Pre-screen API call failed (%s) — skipping filter, proceeding with all %d roles. "
            "Estimated Sonnet cost: ~$%.4f",
            exc, len(jobs), _estimate_sonnet_cost(jobs),
        )
        return jobs

    raw   = response.content[0].text.strip()
    usage = response.usage
    log.info(
        f"Pre-screen ({PRESCREEN_MODEL}) — "
        f"input: {usage.input_tokens} tok, output: {usage.output_tokens} tok"
    )

    # Parse lines like "1. Y", "2. N", "3 Y", "4) N", etc.
    passed: list[dict] = []
    n_filtered         = 0
    matched: set[int]  = set()
    for line in raw.splitlines():
        m = re.match(r"(\d+)[.):\s]+([YN])", line.strip(), re.IGNORECASE)
        if m:
            idx     = int(m.group(1)) - 1
            verdict = m.group(2).upper()
            if 0 <= idx < len(jobs) and idx not in matched:
                matched.add(idx)
                if verdict == "Y":
                    passed.append(jobs[idx])
                else:
                    n_filtered += 1

    if not passed and n_filtered == 0:
        log.warning(
            "Pre-screen: response couldn't be parsed — proceeding with all %d roles. "
            "Estimated Sonnet cost: ~$%.4f",
            len(jobs), _estimate_sonnet_cost(jobs),
        )
        return jobs

    log.info(f"Pre-screen: {len(passed)}/{len(jobs)} passed ({n_filtered} filtered out)")
    return passed


# ---------------------------------------------------------------------------
# Full scoring (Sonnet)
# ---------------------------------------------------------------------------

def _build_score_system() -> str:
    """Build the scoring system prompt, loading the profile fresh each call."""
    profile = _load_profile()
    name = _candidate_name()

    # Read scoring thresholds from profile.yaml; fall back to safe defaults.
    apply_t, consider_t = 75, 55
    try:
        from .profile import load_profile_yaml
        sc = (load_profile_yaml() or {}).get("scoring", {})
        apply_t    = int(sc.get("apply_threshold",    apply_t))
        consider_t = int(sc.get("consider_threshold", consider_t))
    except Exception:
        pass

    return f"""{profile}

You are a job fit evaluator for {name}.

Given a batch of job listings, return a JSON array — one object per job, same order as input:
[
  {{
    "score": <integer 0-100>,
    "verdict": "apply" | "consider" | "skipped" | "filtered",
    "leveragePoints": ["<short phrase ≤5 words>", ...],
    "frictionPoints": ["<short phrase ≤5 words>", ...],
    "tags": [
      {{"text": "<≤5 words>", "sentiment": "green" | "amber" | "red"}}
    ]
  }},
  ...
]

DEAL-BREAKER RULE (apply before scoring anything else):
  If a role clearly violates any item in the DEAL BREAKERS list above — based on the
  job title, company, industry, or JD content — set score=0, verdict="filtered", and
  add exactly one red tag naming the triggered rule (e.g., {{"text": "deal breaker: mgmt only", "sentiment": "red"}}).
  Set leveragePoints=[] and frictionPoints=[].
  A deal-breaker violation must NEVER produce verdict "apply", "consider", or "skipped".

leveragePoints: 1-2 match explanations. Lead with a 2-4 word topic label, em-dash (—), then a
  tight evidence clause. ~12 words total. No "JD needs" prefix — write naturally.
  BAD:  "JD needs agentic workflow design → DocuSign Navigator agentic flows"
  GOOD: "agentic platform — DocuSign Navigator flows match JD's core workflow need"
  BAD:  "JD wants ML depth → UIUC + model eval"
  GOOD: "ML depth — UIUC Deep Learning for Healthcare + 2k-model eval fits JD"
  BAD:  "0-1 PRD authoring"
  GOOD: "0-1 build — DocuSign Custom Extractions built from zero matches JD scope"

frictionPoints: 1 honest concern, same format. Use [] if no real friction.
  NEVER write placeholder text ("none", "n/a", "none material", "no concerns", etc.).
  BAD:  "none material"
  GOOD: []
  BAD:  "JD expects crawl/index infra exp → no direct background"
  GOOD: "crawl/index infra — no direct background, though ML systems work overlaps"

tags: Up to 4 highlight tags. "green" = clear JD↔background match, "amber" = caution or
      domain gap, "red" = hard blocker. ≤5 words each.

Thresholds (from your profile.yaml scoring section):
  score >= {apply_t}  →  apply
  score {consider_t}–{apply_t - 1}  →  consider
  score < {consider_t}   →  skipped
  deal_breaker violated  →  filtered (score=0, overrides all thresholds)

Be honest. {apply_t}% IS strong at this level. Do not inflate.
Return ONLY valid JSON array — no markdown fences, no preamble."""


def score_jobs_batch(client: anthropic.Anthropic, jobs: list[dict]) -> list[dict]:
    job_blocks = "\n\n---\n\n".join(
        "JOB {n}: {title} at {company} ({location})\n{jd_line}".format(
            n=i + 1,
            title=j["title"],
            company=j["company"],
            location=j["location"],
            jd_line=(
                "JD:\n" + j["jd"][:1500]
                if j.get("jd")
                else "(No JD retrieved — score from title/company only)"
            ),
        )
        for i, j in enumerate(jobs)
    )

    response = client.messages.create(
        model=MODEL,
        max_tokens=4096,
        system=[
            {
                "type": "text",
                "text": _build_score_system(),
                "cache_control": {"type": "ephemeral"},
            }
        ],
        messages=[{
            "role": "user",
            "content": (
                f"Score all {len(jobs)} jobs. "
                f"Return a JSON array of exactly {len(jobs)} objects.\n\n"
                f"{job_blocks}"
            ),
        }],
    )

    usage = response.usage
    log.info(
        f"Scoring — input: {usage.input_tokens} tokens "
        f"(cache_write: {getattr(usage, 'cache_creation_input_tokens', 0)}, "
        f"cache_read: {getattr(usage, 'cache_read_input_tokens', 0)}), "
        f"output: {usage.output_tokens} tokens"
    )

    raw = re.sub(
        r"^```(?:json)?\s*|\s*```$", "", response.content[0].text.strip(), flags=re.MULTILINE
    ).strip()
    try:
        evals = json.loads(raw)
        if isinstance(evals, dict):
            evals = [evals]
    except json.JSONDecodeError:
        evals = _recover_partial_json(raw)
        if evals:
            log.warning(
                "Batch score JSON was truncated — recovered %d/%d objects via partial parse",
                len(evals), len(jobs),
            )
        else:
            log.error(
                "Batch score JSON parse failed entirely — all %d jobs marked skipped. "
                "Re-run with a smaller batch or check API token limits.",
                len(jobs),
            )

    _error_eval = {"score": 0, "verdict": "skipped", "leveragePoints": [], "frictionPoints": ["Scoring parse error"], "tags": []}
    for i, job in enumerate(jobs):
        job["eval"] = evals[i] if i < len(evals) else _error_eval
    return jobs


def rank_jobs(jobs: list[dict]) -> list[dict]:
    """Sort jobs by verdict + score, re-deriving verdicts from thresholds first.

    Claude is instructed on thresholds but doesn't guarantee compliance —
    re-validating here ensures a score of 62 is never promoted to "apply".
    """
    apply_t, consider_t = 75, 55
    try:
        from .profile import load_profile_yaml
        sc = (load_profile_yaml() or {}).get("scoring", {})
        apply_t    = int(sc.get("apply_threshold",    apply_t))
        consider_t = int(sc.get("consider_threshold", consider_t))
    except Exception:
        pass

    for job in jobs:
        ev    = job.setdefault("eval", {})
        score = ev.get("score", 0)
        # "filtered" is set by Claude when a deal_breaker is violated — preserve it;
        # don't let a score of 0 accidentally demote it to "skipped".
        if ev.get("verdict") == "filtered":
            pass
        elif score >= apply_t:
            ev["verdict"] = "apply"
        elif score >= consider_t:
            ev["verdict"] = "consider"
        else:
            ev["verdict"] = "skipped"

    order = {"apply": 0, "consider": 1, "skipped": 2, "filtered": 3}
    return sorted(jobs, key=lambda j: (
        order.get(j["eval"].get("verdict", "skipped"), 3),
        -j["eval"].get("score", 0),
    ))
